interface AppConfig {
    endPoints: any;
    routes: any;
    baseUrl: string;
}

export const AppConfig: AppConfig = {
    endPoints: {
        addConfigCohort: 'ConfigCohorts/AddConfigCohorts',
        updateCohort: 'ConfigCohorts/UpdateConfigCohorts',
        getAllCohorts: 'ConfigCohorts/GetAllConfigCohorts',
        deleteCohort: 'ConfigCohorts/DeleteConfigCohorts',
        copyCohorts: 'ConfigCohorts/CopyConfigCohorts',
        deleteMultiCohorts: 'ConfigCohorts/DeleteMultipleConfigCohorts',

        addConfigCurve: 'ConfigCurves/AddConfigCurves',
        getAllCurves: 'ConfigCurves/GetAllConfigCurves',
        updateCurve: 'ConfigCurves/UpdateConfigCurves',
        deleteCurve: 'ConfigCurves/DeleteConfigCurves',
        copyCurves: 'ConfigCurves/CopyConfigCurves',
        deleteMultiCurves: 'ConfigCurves/DeleteMultipleConfigCurves',

        addConfigField: 'ConfigFields/AddConfigFields',
        getAllFields: 'ConfigFields/GetAllConfigFields',
        updateField: 'ConfigFields/UpdateConfigFields',
        deleteField: 'ConfigFields/DeleteConfigFields',
        copyFields: 'ConfigFields/CopyConfigFields',
        deleteMultiFields: 'ConfigFields/DeleteMultipleConfigFields',

        addConfigPoFBand: 'ConfigPoFBands/AddConfigPoFBands',
        getAllPoFBands: 'ConfigPoFBands/GetAllConfigPoFBands',
        updatePoFBand: 'ConfigPoFBands/UpdateConfigPoFBands',
        deletePoFBand: 'ConfigPoFBands/DeleteConfigPoFBands',
        copyPoFBands: 'ConfigPoFBands/CopyConfigPoFBands',
        deleteMultiPoFBands: 'ConfigPoFBands/DeleteMultipleConfigPoFbands',

        addConfigRiskLevel: 'ConfigRiskLevels/AddConfigRiskLevels',
        getAllRiskLevels: 'ConfigRiskLevels/GetAllConfigRiskLevels',
        updateRiskLevel: 'ConfigRiskLevels/UpdateConfigRiskLevels',
        deleteRiskLevel: 'ConfigRiskLevels/DeleteConfigRiskLevels',
        copyRiskLevels: 'ConfigRiskLevels/CopyConfigRiskLevels',
        deleteMultiRiskLevels: 'ConfigRiskLevels/DeleteMultipleConfigRiskLevels',

        addConfigScenario: 'ConfigScenarios/AddConfigScenarios',
        getAllScenarios: 'ConfigScenarios/GetAllConfigScenarios',
        updateScenario: 'ConfigScenarios/UpdateConfigScenarios',
        deleteScenario: 'ConfigScenarios/DeleteConfigScenarios',
        copyScenarios: 'ConfigScenarios/CopyConfigScenarios',
        deleteMultiScenarios: 'ConfigScenarios/DeleteMultipleConfigScenarios',

        addModelConfig: 'ModelConfiguration/AddModelConfiguration',
        getAllConfigs: 'ModelConfiguration/GetAllModelConfiguration',
        updateConfig: 'ModelConfiguration/UpdateModelConfiguration',
        deleteConfig: 'ModelConfiguration/DeleteModelConfiguration',
        runModels: 'RunHistory/AddModelConfigurationRunHistory',
        copyModels: 'ModelConfiguration/CopyModelConfiguration',
        deleteMultiModels: 'ModelConfiguration/DeleteMultipleModelConfigurations',

        addConfigBudget: 'ConfigBudget/AddConfigBudget',
        getAllBudgets: 'ConfigBudget/GetAllConfigBudget',
        updateBudget: 'ConfigBudget/UpdateConfigBudget',
        deleteBudget: 'ConfigBudget/DeleteConfigBudget',
        copyBudgets: 'ConfigBudget/CopyConfigBudget',
        deleteMultiBudgets :'ConfigBudget/DeleteMultipleConfigBudgets',

        addConfigBudgetYear: 'ConfigBudgetYear/AddConfigBudgetYear',
        getAllBudgetYears: 'ConfigBudgetYear/GetAllConfigBudgetYear',
        updateBudgetYear: 'ConfigBudgetYear/UpdateConfigBudgetYear',
        deleteBudgetYear: 'ConfigBudgetYear/DeleteConfigBudgetYear',
        copyBudgetYears: 'ConfigBudgetYear/CopyConfigBudgetYear',
        deleteMultiBudgetYears: 'ConfigBudgetYear/DeleteMultipleConfigBudgetYears',
        deleteBudgetYearByBudgetId: 'ConfigBudgetYear/DeleteAllConfigBudgetYearsByBudgetId',

        addConfigInterventionOptions: 'ConfigInterventionOptions/AddConfigInterventionOptions',
        getAllInterventionOptions: 'ConfigInterventionOptions/GetAllConfigInterventionOptions',
        updateInterventionOption: 'ConfigInterventionOptions/UpdateConfigInterventionOptions',
        deleteInterventionOption: 'ConfigInterventionOptions/DeleteConfigInterventionOptions',
        copyInterventionOptions: 'ConfigInterventionOptions/CopyConfigInterventionOptions',
        deleteMultiIntOptions: 'ConfigInterventionOptions/DeleteMultipleConfigInterventionOptions',

        addConfigRates: 'ConfigRates/AddConfigRates',
        getAllRates: 'ConfigRates/GetAllConfigRates',
        updateRate: 'ConfigRates/UpdateConfigRates',
        deleteRate: 'ConfigRates/DeleteConfigRates',
        copyRates: 'ConfigRates/CopyConfigRates',
        deleteMultiRates: 'ConfigRates/DeleteMultipleConfigRates',

        addConfigRiskBasedDecision: 'ConfigRiskBasedDecisions/AddConfigRiskBasedDecisions',
        getAllRiskBasedDecisions: 'ConfigRiskBasedDecisions/GetAllConfigRiskBasedDecisions',
        updateRiskBasedDecision: 'ConfigRiskBasedDecisions/UpdateConfigRiskBasedDecisions',
        deleteRiskBasedDecision: 'ConfigRiskBasedDecisions/DeleteConfigRiskBasedDecisions',
        copyRiskBasedDecisions: 'ConfigRiskBasedDecisions/CopyConfigRiskBasedDecisions',
        deleteMultiRiskBasedDecisions: 'ConfigRiskBasedDecisions/DeleteMultipleConfigRiskBasedDecisions',
        
        addConfigLists: 'ConfigLists/AddConfigLists',
        getAllLists: 'ConfigLists/GetAllConfigLists',
        updateList: 'ConfigLists/UpdateConfigLists',
        deleteList: 'ConfigLists/DeleteConfigLists',
        copyLists: 'ConfigLists/CopyConfigLists',
        deleteMultiLists: 'ConfigLists/DeleteMultipleConfigLists',

        addConfigListValues: 'ConfigListValues/AddConfigListValues',
        getAllListValues: 'ConfigListValues/GetAllConfigListValues',
        updateListValue: 'ConfigListValues/UpdateConfigListValues',
        deleteListValue: 'ConfigListValues/DeleteConfigListValues',
        copyListValues: 'ConfigListValues/CopyConfigListValues',
        deleteMultiListValues: 'ConfigListValues/DeleteMultipleConfigListValues',
        getListValuesByListId: 'ConfigListValues/GetConfigListValuesByListId',

        getAllRunHistory: 'RunHistory/GetAllRunHistory',

        lookupSkipTheseLifecycles: 'Lookup/LookupSkipTheseLifecycles',
        lookupSkipTheseAssetSources: 'Lookup/LookupSkipTheseAssetSources',
        lookupSkipTheseUnitClasses: 'Lookup/LookupSkipTheseUnitClasses',
        lookupConfigScenarios: 'Lookup/LookupConfigScenarios',
        lookupConfigCohorts : 'Lookup/LookupConfigCohorts',

        budgetPivotDetails: 'BudgetDetails/GetAllConfigBudgetPivotDetails',
    },
    routes: {
        projects: {
            plans: "Projects/Plans",
        },
        data_model: "Data-Model",
        add: {
            doNothing: "add-config-model",
            cohort: "add-config-cohort",
            configScenarios: "add-config-scenarios",
            configFields: "add-config-fields",
            configRiskLevels: "add-config-riskLevels",
            configCurves: "add-config-curves",
            pofBands: "add-config-pof-bands",
            configBudget: "add-config-budget",
            configBudgetYear: "add-config-budget-year",
            configInterventionOptions: "add-config-interventionOptions",
            configRates: "add-config-rates",
            configRiskBasedDecision: "add-config-riskBasedDecision",
            configLists: "add-config-lists",
            configListValues: "add-config-listValues",
        },
        edit: {
            doNothing: "edit-config-model",
            configCohort: "edit-config-cohort",
            configScenarios: "edit-config-scenarios",
            configFields: "edit-config-fields",
            configRiskLevels: "edit-config-risk-levels",
            configCurves: "edit-config-curves",
            pofBands: "edit-config-pof-bands",
            configBudget: "edit-config-budget",
            configBudgetYear: "edit-config-budget-year",
            configInterventionOptions: "edit-config-interventionOptions",
            configRates: "edit-config-rates",
            configRiskBasedDecision: "edit-config-riskBasedDecision",
            configLists: "edit-config-lists",
            configListValues: "edit-config-listValues"
        },
        view: {
            curvesTable: "curves-table",
            cohortTable: "cohort-table",
            scenariosTable: "scenarios-table",
            fieldsTable: "fields-table",
            riskLevelsTable: "risk-levels-table",
            pofBandsTable: "pof-bands-table",
            doNothingTable: "model-table",
            listsTable: "lists-table",
            listValuesTable: "list-values-table",
            ratesTable: "rates-table",
            budgetTable: "budget-table",
            budgetYearsTable: "budget-years-table",
            interventionOptionsTable: "intervention-options-table",
            riskBasedDecisionTable: "risk-based-decision-table",
            runHistory: "run-history-table",
        },
        // exportModel: "export-models"
    },
    baseUrl: 'https://localhost:44360/'
};
